src/Entity/Formation.php
<?php

namespace App\Entity;

use App\Entity\User;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use App\Repository\FormationRepository;

#[ORM\Entity(repositoryClass: FormationRepository::class)]
#[ORM\Table(name: "tbl_formation")]

class Formation
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $name = null;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $content = null;

    #[ORM\Column(nullable: true)]
    private ?int $capacity = null;

    #[ORM\Column(nullable: true)]
    private ?float $price = null;

    #[ORM\ManyToOne(inversedBy: 'formations')]
    private ?User $speaker = null;

    #[ORM\Column(nullable: true)]
    private ?\DateTimeImmutable $createdAt = null;

    #[ORM\ManyToOne(inversedBy: 'formationsCreatedBy')]
    private ?User $createdBy = null;


    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $description = null;

    #[ORM\Column(nullable: true)]
    private ?\DateTimeImmutable $startDateTime = null;

    #[ORM\Column(nullable: true)]
    private ?\DateTimeImmutable $endDateTime = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $image_file_name = null;


    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getContent(): ?string
    {
        return $this->content;
    }

    public function setContent(?string $content): self
    {
        $this->content = $content;

        return $this;
    }

    public function getCapacity(): ?int
    {
        return $this->capacity;
    }

    public function setCapacity(?int $capacity): self
    {
        $this->capacity = $capacity;

        return $this;
    }

    public function getPrice(): ?float
    {
        return $this->price;
    }

    public function setPrice(?float $price): self
    {
        $this->price = $price;

        return $this;
    }

    public function getSpeaker(): ?User
    {
        return $this->speaker;
    }

    public function setSpeaker(?User $speaker): self
    {
        $this->speaker = $speaker;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeImmutable
    {
        return $this->createdAt;
    }

    public function setCreatedAt(?\DateTimeImmutable $createdAt): self
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    public function getCreatedBy(): ?User
    {
        return $this->createdBy;
    }

    public function setCreatedBy(?User $createdBy): self
    {
        $this->createdBy = $createdBy;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getStartDateTime(): ?\DateTimeImmutable
    {
        return $this->startDateTime;
    }

    public function setStartDateTime(?\DateTimeImmutable $startDateTime): self
    {
        $this->startDateTime = $startDateTime;

        return $this;
    }

    public function getEndDateTime(): ?\DateTimeImmutable
    {
        return $this->endDateTime;
    }

    public function setEndDateTime(?\DateTimeImmutable $endDateTime): self
    {
        $this->endDateTime = $endDateTime;

        return $this;
    }

    public function getImageFileName(): ?string
    {
        return $this->image_file_name;
    }

    public function setImageFileName(?string $image_file_name): self
    {
        $this->image_file_name = $image_file_name;

        return $this;
    }


}

src/Form/FormationType.php
<?php

namespace App\Form;

use App\Entity\Formation;
use Symfony\Component\Form\AbstractType;
use FOS\CKEditorBundle\Form\Type\CKEditorType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\Validator\Constraints\File;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Contracts\Translation\TranslatorInterface;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\Extension\Core\Type\FileType;

class FormationType extends AbstractType
{
    private $translator;

    public function __construct(TranslatorInterface $translator){
        $this->translator = $translator;
    }

    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder->add('name');
            $builder->add('content', CKEditorType::class);
            $builder->add('capacity');
            $builder->add('price');
            // $builder->add('createdAt');
            $builder->add('description');
            $builder->add('startDateTime',  DateType::class, [
                'widget' => 'single_text',
                'format' => 'yyyy-MM-dd',
                'input'  => 'datetime_immutable',
            ]);
            $builder->add('endDateTime',  DateType::class, [
                'widget' => 'single_text',
                'format' => 'yyyy-MM-dd',
                'input'  => 'datetime_immutable',
            ]);
            $builder->add('speaker');
            $builder->add('createdBy');
        
            $builder->add('image', FileType::class, [
            'label' => $this->translator->trans('Illustration'),

            // unmapped means that this field is not associated to any entity property
            'mapped' => false,

            // make it optional so you don't have to re-upload the PDF file
            // every time you edit the Product details
            'required' => false,

            // unmapped fields can't define their validation using annotations
            // in the associated entity, so you can use the PHP constraint classes
            'constraints' => [
                new File([
                    'maxSize' => '1024k',
                    'mimeTypes' => [
                        'image/jpg',
                        'image/jpeg',
                        'image/png',
                    ],
                    'mimeTypesMessage' => $this->translator->trans('Please upload a valid image file'),
                ])
            ],
        ]);
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Formation::class,
        ]);
    }
}

src/Controller/FormationController.php
<?php

namespace App\Controller;

use DateTimeImmutable;
use App\Entity\Formation;
use App\Form\FormationType;
use App\Services\ImageUploaderHelper;
use App\Repository\FormationRepository;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\String\Slugger\SluggerInterface;
use Symfony\Contracts\Translation\TranslatorInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

#[Route('/formation')]
class FormationController extends AbstractController
{

    #[Route('/pdf/{id}', name: 'app_formation_pdf', methods: ['GET'])]
    public function pdf(Formation $formation): Response
    {
        $pdf = new \TCPDF();

        $pdf->SetAuthor('SIO1 team');
        $pdf->SetTitle($formation->getName());
        $pdf->setCellPaddings(1, 1, 1, 1);
        $pdf->setCellMargins(1, 1, 1, 1);

        $pdf->AddPage();

        $pdf->SetXY(10, 10);
        $pdf->Image('fcpro3.png');  

        $pdf->SetXY(10, 30);
        $pdf->SetFillColor(255, 255, 255);
        $pdf->SetFont('helvetica', '', 18);
        $pdf->SetTextColor(0, 0, 255);
        $pdf->MultiCell(185, 10, $formation->getName(), 0, 'P', 1, 0, '', '', true);

        $pdf->SetXY(10, 55);
        $pdf->SetFillColor(240, 240, 240);
        $pdf->SetFont('times', '', 12);
        $pdf->SetTextColor(0, 0, 255);
        $pdf->writeHTML($formation->getContent());

        
        return $pdf->Output('fcpro-formation-' . $formation->getId() . '.pdf', 'I');
    }

    #[Route('/futur', name: 'app_formation_futur', methods: ['GET'])]
    public function futur(FormationRepository $formationRepository): Response
    {
        $formationsPerThree = array();

        $formations = $formationRepository->findAllInTheFutur();

        $i = 0;
        $j = 1;
        foreach ($formations as $formation){
            $i++;
            if($i>3){
            $j++; $i=1;
            }
        $formationsPerThree[$j][$i] = $formation;
        }
        dump($formation);
        dump($formationsPerThree);

        return $this->render('formation/catalog.html.twig', [
            'formations' => $formationRepository->findAllInTheFuture(),
        ]);
    }

    #[Route('/catalog', name: 'app_formation_catalog', methods: ['GET'])]
    public function catalog(FormationRepository $formationRepository): Response
    {
        return $this->render('formation/catalog.html.twig', [
            'formations' => $formationRepository->findAllInTheFuture(),
        ]);
    }

    #[Route('/', name: 'app_formation_index', methods: ['GET'])]
    public function index(FormationRepository $formationRepository): Response
    {
        return $this->render('formation/index.html.twig', [
            'formations' => $formationRepository->findAllInTheFuture(),
        ]);
    }

    #[Route('/new', name: 'app_formation_new', methods: ['GET', 'POST'])]
    public function new(Request $request, FormationRepository $formationRepository): Response
    {
        $this->denyAccessUnlessGranted('ROLE_ADMIN');
        $formation = new Formation();
        $formation->setCreatedAt(new DateTimeImmutable());
        $formation->setCreatedBy($this->getUser());
        $form = $this->createForm(FormationType::class, $formation);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $formationRepository->save($formation, true);

            return $this->redirectToRoute('app_formation_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('formation/new.html.twig', [
            'formation' => $formation,
            'form' => $form,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_formation_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, ImageUploaderHelper $imageUploaderHelper, Formation $formation, FormationRepository $formationRepository, TranslatorInterface $translator): Response
    {
        $this->denyAccessUnlessGranted('ROLE_ADMIN');

        $form = $this->createForm(FormationType::class, $formation);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            
            $errorMessage = $imageUploaderHelper->uploadImage($form, $formation);
            if(!empty($errorMessage)){
                $ths->addFlash('danger', $translator->trans('An error is append: ') . $errorMessage);
            }

            $formationRepository->save($formation, true);

            return $this->redirectToRoute('app_formation_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('formation/edit.html.twig', [
            'formation' => $formation,
            'form' => $form,
        ]);
    }

    #[Route('/{id}/copy', name: 'app_formation_copy', methods: ['GET', 'POST'])]
    public function copy(Request $request, ImageUploaderHelper $imageUploaderHelper, Formation $formation, FormationRepository $formationRepository, TranslatorInterface $translator): Response
    {
        $this->denyAccessUnlessGranted('ROLE_ADMIN');

        $formation2 = new Formation();
        $formation2->setCreatedAt($formation->getCreatedAt());
        $formation2->setCreatedBy($formation->getCreatedBy());
        $formation2->setContent($formation->getContent());
        $formation2->setDescription($formation->getDescription());

        $formation2->setCapacity($formation->getCapacity());
        $formation2->setStartDateTime($formation->getStartDateTime());
        $formation2->setEndDateTime($formation->getEndDateTime());
        $formation2->setImageFileName($formation->getImageFileName());
        $formation2->setName($formation->getName());
        $formation2->setPrice($formation->getPrice());

            $formationRepository->save($formation2, true);
            $this->addFlash('success', $translator->trans('The formation is copied '));

            return $this->redirectToRoute('app_formation_index');
    }
    
    #[Route('/{id}', name: 'app_formation_show', methods: ['GET'])]
    public function show(Formation $formation): Response
    {
        return $this->render('formation/show.html.twig', [
            'formation' => $formation,
        ]);
    }

    #[Route('/{id}', name: 'app_formation_delete', methods: ['POST'])]
    public function delete(Request $request, Formation $formation, FormationRepository $formationRepository): Response
    {
        $this->denyAccessUnlessGranted('ROLE_ADMIN');
        if ($this->isCsrfTokenValid('delete'.$formation->getId(), $request->request->get('_token'))) {
            $formationRepository->remove($formation, true);
        }

        return $this->redirectToRoute('app_formation_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/formation/_delete_form.html.twig
<form method="post" action="{{ path('app_formation_delete', {'id': formation.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ formation.id) }}">
    <button class="btn">Delete</button>
</form>

templates/formation/_form.html.twig
{{ form_start(form) }}


<div class="row">
    <div class="col">
        <img 
        width="300" height="300" src="{{ asset('uploads/images/' ~ formation.imageFileName) }}">
        {{ form_row(form.image) }}
    </div>   
    <div class="col">   
        {{ form_row(form.name) }}
    </div>
</div>


    {{ form_row(form.content) }}

    <div class="row">
        <div class="col">{{ form_row(form.capacity)  }}</div>
        <div class="col">{{ form_row(form.price)     }}</div>
    </div>
    
    <div class="row">
        <div class="col">{{ form_row(form.startDateTime) }}</div>
        <div class="col">{{ form_row(form.endDateTime)   }}</div>
    </div>

    <div class="row">
        <div class="col">{{ form_row(form.speaker)      }}</div>
        <div class="col">{{ form_row(form.createdBy)    }}</div>
    </div>

    {{ form_row(form.description)  }}

    <button class="btn btn-primary">{{ button_label|default('Save' | trans) }}</button>
{{ form_end(form) }}

templates/formation/catalog.html.twig
{% extends 'base.html.twig' %}

{% block title %}Formation index{% endblock %}

{% block body %}
    <h1>Formation index</h1>

    {% set number = 0 %}
        {% for formation in formations %}
        {% set number = number + 1 %}
        <div class="accordion" id={{ formation.name }}>
            <div class="accordion-item">
              <h2 class="accordion-header">
                <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#collapse-{{ formation.name }}" aria-expanded="true" aria-controls="collapse-{{ formation.name }}">
                  {{ formation.name }}
                </button>
              </h2>
              <div id="collapse-{{ formation.name }}" class="accordion-collapse collapse {% if number <2 %} show {% endif %}" data-bs-parent="#accordionExample">
                <div class="accordion-body">
                  <strong>Description : </strong> {{ formation.description }}
                  <br/>
                  <a class="btn btn-primary" href="/formation/pdf/{{ formation.id }}" target="_blank">{{ 'Download PDF' | trans }}</a>
                </div>
            </div>
        </div>

        {% else %}
            <tr>
                <td colspan="10">no records found</td>
            </tr>
        {% endfor %}
        </div>
    

{% endblock %}

templates/formation/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Formation{% endblock %}

{% block body %}
    <h1>Edit Formation</h1>

    {{ include('formation/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_formation_index') }}">back to list</a>

    {{ include('formation/_delete_form.html.twig') }}
{% endblock %}

templates/formation/futur.html.twig
{% extends 'base.html.twig' %}

{% block title %}Formation index{% endblock %}

{% block body %}
    <h1>Formation index</h1>

  <div id="carouselExample" class="carousel slide">
      <div class="carousel-inner">
        <div class="carousel-item active">
          <table border="1">
          <tr>
            <td>
              <div class="card" style="width: 15rem;">
                <img src="/img/800x400.png" class="card-img-top" alt="...">
                <div class="card-body">
                  <h5 class="card-title">Card title</h5>
                  <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
                  <a href="#" class="btn btn-primary">Go somewhere</a>
                </div>
              </div>
            </td>
            <td>
              <div class="card" style="width: 15rem;">
                <img src="/img/800x400.png" class="card-img-top" alt="...">
                <div class="card-body">
                  <h5 class="card-title">Card title</h5>
                  <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
                  <a href="#" class="btn btn-primary">Go somewhere</a>
                </div>
              </div>
            </td>
            <td>
              <div class="card" style="width: 15rem;">
                <img src="/img/800x400.png" class="card-img-top" alt="...">
                <div class="card-body">
                  <h5 class="card-title">Card title</h5>
                  <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
                  <a href="#" class="btn btn-primary">Go somewhere</a>
                </div>
              </div>
            </td>
          </tr>
        </table>
        </div>
        <div class="carousel-item">
          <table border="1">
            <tr>
              <td>
                <div class="card" style="width: 15rem;">
                  <img src="/img/800x400.png" class="card-img-top" alt="...">
                  <div class="card-body">
                    <h5 class="card-title">Card title</h5>
                    <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
                    <a href="#" class="btn btn-primary">Go somewhere</a>
                  </div>
                </div>
              </td>
              <td>
                <div class="card" style="width: 15rem;">
                  <img src="/img/800x400.png" class="card-img-top" alt="...">
                  <div class="card-body">
                    <h5 class="card-title">Card title</h5>
                    <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
                    <a href="#" class="btn btn-primary">Go somewhere</a>
                  </div>
                </div>
              </td>
              <td>
                <div class="card" style="width: 15rem;">
                  <img src="/img/800x400.png" class="card-img-top" alt="...">
                  <div class="card-body">
                    <h5 class="card-title">Card title</h5>
                    <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
                    <a href="#" class="btn btn-primary">Go somewhere</a>
                  </div>
                </div>
              </td>
            </tr>
          </table>
        </div>
        <div class="carousel-item">
          <table border="1">
            <tr>
              <td>
                <div class="card" style="width: 15rem;">
                  <img src="/img/800x400.png" class="card-img-top" alt="...">
                  <div class="card-body">
                    <h5 class="card-title">Card title</h5>
                    <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
                    <a href="#" class="btn btn-primary">Go somewhere</a>
                  </div>
                </div>
              </td>
              <td>
                <div class="card" style="width: 15rem;">
                  <img src="/img/800x400.png" class="card-img-top" alt="...">
                  <div class="card-body">
                    <h5 class="card-title">Card title</h5>
                    <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
                    <a href="#" class="btn btn-primary">Go somewhere</a>
                  </div>
                </div>
              </td>
              <td>
                <div class="card" style="width: 15rem;">
                  <img src="/img/800x400.png" class="card-img-top" alt="...">
                  <div class="card-body">
                    <h5 class="card-title">Card title</h5>
                    <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
                    <a href="#" class="btn btn-primary">Go somewhere</a>
                  </div>
                </div>
              </td>
            </tr>
          </table>
        </div>
      </div>
      <button class="carousel-control-prev" type="button" data-bs-target="#carouselExample" data-bs-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Previous</span>
      </button>
      <button class="carousel-control-next" type="button" data-bs-target="#carouselExample" data-bs-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Next</span>
      </button>
    </div>
</div>

templates/formation/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Formation index{% endblock %}

{% block body %}
    <h1>Formation index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Name</th>
                <!--<th>Content</th>-->
                <th>Capacity</th>
                <th>Price</th>
                <th>CreatedAt</th>
                <!--<th>Description</th>-->
                <th>StartDateTime</th>
                <th>EndDateTime</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for formation in formations %}
            <tr>
                <td>{{ formation.id }}</td>
                <td>{{ formation.name }}</td>
                <!--<td>{{ formation.content }}</td>-->
                <td>{{ formation.capacity }}</td>
                <td>{{ formation.price }}</td>
                <td>{{ formation.createdAt ? formation.createdAt|date('Y-m-d H:i:s') : '' }}</td>
                <!--<td>{{ formation.description }}</td>-->
                <td>{{ formation.startDateTime ? formation.startDateTime|date('Y-m-d H:i:s') : '' }}</td>
                <td>{{ formation.endDateTime ? formation.endDateTime|date('Y-m-d H:i:s') : '' }}</td>
                <td>
                    <a class="btn btn-primary" href="{{ path('app_formation_show', {'id': formation.id}) }}">show</a>
                    <a class="btn btn-warning" href="{{ path('app_formation_edit', {'id': formation.id}) }}">edit</a>
                    <a class="btn btn-warning" href="{{ path('app_formation_copy', {'id': formation.id}) }}">copy</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="10">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('app_formation_new') }}">Create new</a>
{% endblock %}

templates/formation/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Formation{% endblock %}

{% block body %}
    <h1>Create new Formation</h1>

    {{ include('formation/_form.html.twig') }}

    <a href="{{ path('app_formation_index') }}">back to list</a>
{% endblock %}

templates/formation/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Formation{% endblock %}

{% block body %}
    <h1>Formation</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ formation.id }}</td>
            </tr>
            <tr>
                <th>Name</th>
                <td>{{ formation.name }}</td>
            </tr>
            <tr>
                <th>Content</th>
                <td>{{ formation.content }}</td>
            </tr>
            <tr>
                <th>Capacity</th>
                <td>{{ formation.capacity }}</td>
            </tr>
            <tr>
                <th>Price</th>
                <td>{{ formation.price }}</td>
            </tr>
            <tr>
                <th>CreatedAt</th>
                <td>{{ formation.createdAt ? formation.createdAt|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>Description</th>
                <td>{{ formation.description }}</td>
            </tr>
            <tr>
                <th>StartDateTime</th>
                <td>{{ formation.startDateTime ? formation.startDateTime|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>EndDateTime</th>
                <td>{{ formation.endDateTime ? formation.endDateTime|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_formation_index') }}">back to list</a>

    <a href="{{ path('app_formation_edit', {'id': formation.id}) }}">edit</a>

    {{ include('formation/_delete_form.html.twig') }}
{% endblock %}